language: bash
services: docker

env:
  - VERSION=jdk7
  - VERSION=jdk7 VARIANT=alpine
  - VERSION=jre7
  - VERSION=jre7 VARIANT=alpine
  - VERSION=jdk8
  - VERSION=jdk8 VARIANT=alpine
  - VERSION=jre8
  - VERSION=jre8 VARIANT=alpine
  - VERSION=jdk9
  - VERSION=jre9
  - VERSION=jdk10
  - VERSION=jre10
  - VERSION=jdk11
  - VERSION=jre11

before_install:
  - env | sort
  - cd "${VERSION}${VARIANT:+-$VARIANT}"
  - image="gradle:${VERSION}${VARIANT:+-$VARIANT}"
  - docker rmi "${image}" || true
  - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f

install:
  - docker build --tag "${image}" .

script:
  - cd ../test
  - ./run.sh "${image}" "4.8.1"
